workflows:
  build-ios:
    environment:
      flutter: beta

    scripts:
      # Fetch dependencies
      - flutter pub get

      # Build the iOS app
      - flutter build ios

    artifacts:
      - build/ios/iphoneos/*.app  
