workflows:
  build-ios:
    environment:
      flutter: "2.2.0"  # Specify the desired Flutter version

    scripts:
      # Fetch dependencies
      - flutter pub get

      # Build the iOS app
      - flutter build ios

    artifacts:
      - build/ios/iphoneos/*.app  
